name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ../../bin/mailhog/Dockerfile --file Dockerfile --tag gottschalt92/mailhog_mail_tester:$(date +%s)
